package in.virit.libcamera4j;

import java.util.Iterator;
import java.util.NoSuchElementException;

/**
 * Represents a complete camera configuration with one or more streams.
 *
 * <p>A CameraConfiguration is generated by {@link Camera#generateConfiguration(StreamRole...)}
 * and can be modified before being applied with {@link Camera#configure(CameraConfiguration)}.</p>
 */
public class CameraConfiguration implements Iterable<StreamConfiguration>, AutoCloseable {

    static {
        NativeLoader.load();
    }

    /**
     * Status of configuration validation.
     */
    public enum Status {
        /**
         * Configuration is valid and can be applied as-is.
         */
        VALID(0),

        /**
         * Configuration was adjusted to valid values.
         * The adjusted values may differ from what was requested.
         */
        ADJUSTED(1),

        /**
         * Configuration is invalid and cannot be applied.
         */
        INVALID(2);

        private final int value;

        Status(int value) {
            this.value = value;
        }

        public int value() {
            return value;
        }

        public static Status fromValue(int value) {
            for (Status s : values()) {
                if (s.value == value) {
                    return s;
                }
            }
            return INVALID;
        }
    }

    private long nativeHandle;
    private Status status = Status.VALID;

    CameraConfiguration(long nativeHandle) {
        this.nativeHandle = nativeHandle;
    }

    /**
     * Returns the native handle for this configuration.
     * Used internally for JNI bindings.
     *
     * @return the native handle
     */
    long nativeHandle() {
        return nativeHandle;
    }

    /**
     * Returns the number of stream configurations.
     *
     * @return the number of streams
     */
    public int size() {
        return nativeSize(nativeHandle);
    }

    /**
     * Returns whether the configuration is empty.
     *
     * @return true if there are no stream configurations
     */
    public boolean isEmpty() {
        return size() == 0;
    }

    /**
     * Returns the stream configuration at the specified index.
     *
     * @param index the stream index
     * @return the stream configuration
     * @throws IndexOutOfBoundsException if index is out of range
     */
    public StreamConfiguration get(int index) {
        if (index < 0 || index >= size()) {
            throw new IndexOutOfBoundsException("Index: " + index + ", Size: " + size());
        }
        return new StreamConfiguration(this, index);
    }

    /**
     * Validates the configuration and applies any necessary adjustments.
     *
     * @return the validation status
     */
    public Status validate() {
        int result = nativeValidate(nativeHandle);
        status = Status.fromValue(result);
        return status;
    }

    /**
     * Returns the current validation status.
     *
     * @return the status
     */
    public Status status() {
        return status;
    }

    @Override
    public Iterator<StreamConfiguration> iterator() {
        return new Iterator<>() {
            private int index = 0;
            private final int size = size();

            @Override
            public boolean hasNext() {
                return index < size;
            }

            @Override
            public StreamConfiguration next() {
                if (!hasNext()) {
                    throw new NoSuchElementException();
                }
                return get(index++);
            }
        };
    }

    @Override
    public void close() {
        if (nativeHandle != 0) {
            nativeDestroy(nativeHandle);
            nativeHandle = 0;
        }
    }

    @Override
    public String toString() {
        return "CameraConfiguration[streams=" + size() + ", status=" + status + "]";
    }

    // Native methods
    private native void nativeDestroy(long handle);
    private native int nativeSize(long handle);
    private native int nativeValidate(long handle);

    // Stream configuration access - delegated to StreamConfiguration
    native int nativeGetWidth(long handle, int index);
    native int nativeGetHeight(long handle, int index);
    native int nativeGetStride(long handle, int index);
    native int nativeGetPixelFormat(long handle, int index);
    native void nativeSetSize(long handle, int index, int width, int height);
    native void nativeSetPixelFormat(long handle, int index, int fourcc);
    native void nativeSetBufferCount(long handle, int index, int count);
}
